version: 2.1

orbs:
  wsorb: whitesource/whitesource-scan@20.3.1
  

workflows:
  test:
    jobs:
    - wsorb/scan:
        api_key: '638d73808a2641fba68c0f9ba5408e617545c4403a194db8b3d765fd8767cb59'
        directory: Data/Maven/Data/
        config_file_path:  ./Data/Maven/wss-unified-agent.config
        commands_file_path: "install_commands.sh"
        


         
