source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'a', '~> 0.1.1'
gem 'q', '~> 0.0.1'
gem 'chalk', '~> 0.0.2'
